Switched MQTT go library to support MQTT 5.
edgefarm/alm-service-modules pull request #15
Opened 2021-06-16 13:25 UTC by KairaMiu

2021-06-16 19:04 UTC, KlausPopp requested changes
Please add in Makefile tests to .PHONY: 
.PHONY: clean example test

git commit hook missing

2021-06-17 12:04 UTC, KairaMiu commented on alm-mqtt-module/main.go
>  	natsClient = <-natsClientChan
Done

2021-06-17 12:04 UTC, KairaMiu commented on alm-mqtt-module/main.go
> +			// Connect Client to MQTT Broker
Done

2021-06-17 12:05 UTC, KairaMiu commented on alm-mqtt-module/main.go
> +			// mqttClient.Router.UnregisterHandler(removeMqttTopic)
Removed

2021-06-17 12:22 UTC, KlausPopp approved these changes

2021-06-17 12:23 UTC, merged