Add request response
edgefarm/alm-service-modules pull request #16
Opened 2021-06-17 12:13 UTC by KairaMiu

Added support of MQTT 5 feature Request - Response Pattern

2021-06-17 14:15 UTC, KlausPopp requested changes

2021-06-17 14:15 UTC, KlausPopp commented on alm-mqtt-module/pkg/client/client.go
> +	response, err := c.nats.Request(fmt.Sprintf("%s.request-response", c.target), bytes, 20*time.Second)
timeout should be user's timeout plus some extra

2021-06-17 14:15 UTC, KlausPopp commented on alm-mqtt-module/pkg/schema/avro_schemas/reqResRequest.avsc
> +                "doc": "Sets the timeout for a the request repsose",
Remove "sets the" ("timeout for a the request repsose" is sufficient"

2021-06-18 06:12 UTC, KairaMiu commented on alm-mqtt-module/example/requestReply/requestReply.go
> +Copyright © 2021 edgefarm.io
Done

2021-06-18 06:12 UTC, KairaMiu commented on alm-mqtt-module/example/requestReply/requestReply.go
> +		res, err := client.RequestReply("/pis/cmd/state", b, int32(5000))
Done

2021-06-18 06:15 UTC, KairaMiu commented on alm-mqtt-module/pkg/client/client.go
> +	response, err := c.nats.Request(fmt.Sprintf("%s.request-response", c.target), bytes, 20*time.Second)
Changed to `2 * timeout`

2021-06-18 06:16 UTC, KairaMiu commented on alm-mqtt-module/pkg/schema/avro_schemas/reqResRequest.avsc
> +                "doc": "Sets the timeout for a the request repsose",
Ok

2021-06-18 06:42 UTC, KlausPopp approved these changes

2021-06-18 06:50 UTC, merged